package Nucleos;

public enum TipoDeFallo {
    LW_NOESMIETIEQUETAYMODIFICADO,
    LW_CARGARDESDECACHE,
    LW_CARGARDESDEMEMORIA,
    SW_NOESMIETIEQUETAYMODIFICADO,
    SW_CARGARDESDECACHE,
    SW_CARGARDESDEMEMORIA,
    SW_ESTOYCOMPARTIDO
}
